import { StyleSheet } from "react-native";
import { getStatusBarHeight } from "react-native-iphone-x-helper";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#3048EA",
    alignItems: "center",
    justifyContent: "space-between",
  },
  config:{
    backgroundColor: "#7989EE",
    height:60,
    width:73,
    borderTopLeftRadius:30,
    borderBottomLeftRadius:30,
    justifyContent: "center",
    alignItems: "center",
  },
  panel: {
    width: "100%",
    flex: 1,
    textAlign: "left",
    paddingHorizontal: 24,
    alignItems: "flex-end",
    justifyContent: "center",
    zIndex: 2,
    marginTop: 20,
  },
  header: {
    width: "100%",
    paddingLeft: 24,
    paddingTop: 24,
    flexDirection: "row",
    marginTop: getStatusBarHeight() + 26,
    marginBottom: 20,
    justifyContent: "space-between",
    alignItems: "center",
  },
  backBut: {
    fontFamily: "Poppins_300Light",
    fontSize: 18,
    fontWeight: "400",
    marginBottom: 15,
    color: "#fff",
  },
  title: {
    fontFamily: "Poppins_500Medium",
    fontSize: 30,
    fontWeight: "400",
    marginBottom: 15,
    color: "#fff",
  },
  text: {
    fontFamily: "Poppins_300Light",
    fontSize: 18,
    fontWeight: "400",
    marginBottom: 15,
    color: "#fff",
  },
  image: {
    width: 367,
    height: 437,
    position: "absolute",
    top: 0,
    left: 0,
  },
  info: {
    marginTop: 42,
    backgroundColor: "#fff",
    justifyContent: "space-around",
    width: "100%",
    height: "40%",
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    paddingTop: 25,
    zIndex: 1,
    flexDirection: "row",
  },
  infoItem:{
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});
